[package]
name = "mosin_os"
version = "0.1.0"
authors = ["Ben Olson <molson5@vols.utk.edu>"]
edition = "2018"

[profile.dev]
lto = false
panic = "abort"

[profile.release]
lto = true
panic = "unwind"

[dependencies]

[lib]
crate-type = ["staticlib"]
